In [1]:
import numpy as np
v = np.array([3, 1])
M = np.arange(16)
M = M.reshape(4, 4)

In [2]:
print(v.shape)
print(M.shape)
print(M.dtype)

(2,)
(4, 4)
int64


In [3]:
v + np.array([1, 2])

array([4, 3])

In [4]:
2 * v

array([6, 2])

In [5]:
v * np.array([10, 20])

array([30, 20])

In [6]:
M[0]

array([0, 1, 2, 3])

In [7]:
M[:, 0]


array([ 0,  4,  8, 12])

In [8]:
M[2:4, 2:4]


array([[10, 11],
       [14, 15]])

In [9]:
v.sum()

np.int64(4)

In [11]:
np.dot(v, np.array([1, 2]))

np.int64(5)

In [12]:
v = [2, 5]

In [13]:
v


[2, 5]

In [14]:
M = np.arange(4)


In [15]:
M

array([0, 1, 2, 3])

In [16]:
v + 5


TypeError: can only concatenate list (not "int") to list

In [17]:
v * 2

[2, 5, 2, 5]

In [18]:
sum(v, 2)

9

In [19]:
v.dot(M)


AttributeError: 'list' object has no attribute 'dot'

In [20]:
np.dot(v, M)

ValueError: shapes (2,) and (4,) not aligned: 2 (dim 0) != 4 (dim 0)

In [21]:
np.dot(v, [3, 4])

np.int64(26)

In [22]:
np.ones[3, 4]

TypeError: 'function' object is not subscriptable

In [23]:
np.ones(3, 4)

TypeError: Cannot interpret '4' as a data type

In [24]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.ones(2, 3)

TypeError: Cannot interpret '3' as a data type

In [26]:
print(2 + v)

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [27]:
v = np.array([3, 1])
print(2 + v)

[5 3]


In [28]:
type(v)

numpy.ndarray

In [29]:
v = np.array([3, 1])
w = np.array([1, 2])

In [30]:
print(np.dot(v, w))

5


In [31]:
print(v * w)

[3 2]


In [32]:
print(v * w).sum()

[3 2]


AttributeError: 'NoneType' object has no attribute 'sum'

In [33]:
print((v * w).sum())

5


In [34]:
print(np.dot(v, w) == (v * w).sum())


True
