In [1]:
import numpy as np

A = np.array([[2, 1],
              [1, 3]])

A_inv = np.linalg.inv(A)

print("A =")
print(A)
print("\nA_inv =")
print(A_inv)
print("\nA @ A_inv = ")
print(A @ A_inv)


A =
[[2 1]
 [1 3]]

A_inv =
[[ 0.6 -0.2]
 [-0.2  0.4]]

A @ A_inv = 
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


In [2]:
S = np.array([[2, 4],
              [1, 2]])

det_S = np.linalg.det(S)
print(f"det(S) = {det_S}")

try:
    S_inv = np.linalg.inv(S)
    print(f"S_inv = {S_inv}")
except np.linalg.LinAlgError as e:
    print(f"Expected Error: {e}")

det(S) = 0.0
Expected Error: Singular matrix


In [3]:
print(f"rank(A) = {np.linalg.matrix_rank(A)}")
print(f"rank(S) = {np.linalg.matrix_rank(S)}")

rank(A) = 2
rank(S) = 1


In [4]:
from scipy.linalg import null_space

ns_A = null_space(A)
ns_S = null_space(S)

print(f"Null space of A:\n{ns_A}")
print(f"Shape: {ns_A.shape}")

print(f"Null space of S:\n{ns_S}")
print(f"Shape: {ns_S.shape}")

print(f"\nVerify S crushes its null vector to zero:")
print(f"S @ ns_S = {(S @ ns_S).flatten()}")

Null space of A:
[]
Shape: (2, 0)
Null space of S:
[[ 0.89442719]
 [-0.4472136 ]]
Shape: (2, 1)

Verify S crushes its null vector to zero:
S @ ns_S = [0. 0.]


In [5]:
M = np.array([[1, 0, 1],
              [0, 1, 1],
              [0, 0, 0]])

print("M =")
print(M)
print(f"\nM has 3 columns but rank(M) = {np.linalg.matrix_rank(M)}")
print(f"So ColSpace(M) is {np.linalg.matrix_rank(M)}-dimensional, not 3-dimensional")

target_inside = np.array([3, 5, 0])   # in xy-plane → reachable
target_outside = np.array([3, 5, 1])  # has z-component → unreachable

# For "inside" target: solve Mx = target_inside (least-squares since rank-deficient)
x_inside, residuals_inside, _, _ = np.linalg.lstsq(M, target_inside, rcond=None)
print(f"\nReaching [3,5,0]: M @ x = {M @ x_inside}")
print(f"Match? {np.allclose(M @ x_inside, target_inside)}")

x_outside, residuals_outside, _, _ = np.linalg.lstsq(M, target_outside, rcond=None)
print(f"\nReaching [3,5,1]: M @ x = {M @ x_outside}")
print(f"Match? {np.allclose(M @ x_outside, target_outside)}")

M =
[[1 0 1]
 [0 1 1]
 [0 0 0]]

M has 3 columns but rank(M) = 2
So ColSpace(M) is 2-dimensional, not 3-dimensional

Reaching [3,5,0]: M @ x = [3. 5. 0.]
Match? True

Reaching [3,5,1]: M @ x = [3. 5. 0.]
Match? False
